import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Store, matches, handoffMarkdown } from '../core.mjs';

test('memory lifecycle preserves lineage, permissions, locks, history and portable archives', () => {
  const store = new Store(':memory:');
  const input = { title: 'Database decision', content: 'Use SQLite for local storage.', type: 'semantic', namespace: 'project', tags: ['architecture'], source: 'Architecture discussion' };
  const first = store.save(input);
  const updated = store.save({ ...first, content: 'Use SQLite with WAL mode.' }, undefined, first.id);
  assert.equal(updated.version, 2);
  assert.equal(store.versions(first.id).length, 2);
  assert.equal(store.history('"local storage"').length, 1);
  assert.equal(store.list('type:semantic tag:architecture').length, 1);
  assert(matches(updated, 'namespace:project "WAL mode"'));
  assert.throws(() => store.save({ ...first, content: 'Stale edit' }, undefined, first.id), /changed/);
  store.lock(first.id, true);
  assert.throws(() => store.save(updated, undefined, first.id), /locked/);
  assert.throws(() => store.remove(first.id), /Unlock/);
  store.lock(first.id, false);
  assert.equal(store.versions(first.id).length, 4);
  const secret = store.save({ ...input, title: 'Private note', namespace: 'user', visibility: 'private', content: 'secret-1234' });
  const claude = store.actor('claude');
  assert.equal(store.list('', claude).length, 1);
  assert.throws(() => store.get(secret.id, claude), /permission/);
  assert.throws(() => store.save({ ...input, namespace: 'team' }, claude), /permission/);
  assert.throws(() => store.lock(first.id, true, claude), /owner/);
  store.grant('codex', { namespaces: ['project'], write: false });
  assert.throws(() => store.save(input, store.actor('codex')), /permission/);
  const handoff = store.handoff({ title: 'Resume implementation', target: 'codex', memory_ids: [first.id], notes: 'Implement the API next.' });
  assert(handoffMarkdown(handoff).includes('WAL mode'));
  assert.throws(() => store.handoff({ title: 'Bad handoff', target: 'codex', memory_ids: [secret.id] }), /permission/);
  const exported = store.export();
  const restored = new Store(':memory:');
  assert.equal(restored.import(exported).imported, 2);
  assert.equal(restored.agents().find(a=>a.id==='codex').write,false);
  assert.deepEqual(restored.versions(first.id), store.versions(first.id));
  assert.equal(restored.handoffs().length, 1);
  assert.throws(() => restored.import(exported), /existing/);
  const bad = structuredClone(exported); bad.memories[0].id = 'different';
  const empty = new Store(':memory:');
  assert.throws(() => empty.import(bad));
  assert.equal(empty.list().length, 0);
  const selfReferencing = structuredClone(exported); selfReferencing.memories[0].related=[selfReferencing.memories[0].id];
  assert.throws(()=>empty.import(selfReferencing),/self-reference/);
  const reordered=structuredClone(exported);reordered.memories=reordered.memories.map(m=>Object.fromEntries(Object.entries(m).reverse()));
  empty.grant('claude',{namespaces:[],write:false});
  assert.equal(empty.import(reordered).imported,2);
  assert.deepEqual(empty.agents().find(a=>a.id==='claude').namespaces,[]);
  assert.throws(()=>store.actor('codex','project'),/scope/);
  store.remove(first.id);
  assert.equal(store.handoffs()[0].memories.length, 0);
  assert(!JSON.stringify(store.export()).includes('WAL mode'));
  assert.throws(() => store.save({ ...input, path: 'context://user/escape.md' }), /namespace/);
  assert.throws(() => store.save({ ...input, confidence: 101 }), /Confidence/);
  for (const s of [store, restored, empty]) s.close();
});
